name: Flask App CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # টেস্টের জন্য প্রয়োজনীয় লাইব্রেরি ইনস্টল করা
      - name: Install dependencies
        run: |
          pip install flask pytest

      # আপনার তৈরি করা টেস্ট ফাইলটি রান করা
      - name: Run Pytest
        run: pytest test_app.py

      # টেস্ট পাস করলেই ডকার ইমেজ বিল্ড হবে
      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag flask-app:test
